language: node_js
node_js:
    - '6.2.0'
before_script:
    - 'npm install -g bower'
    - 'npm install -g gulp'
    - 'bower install'
script: gulp travisBuild
notifications:
    slack: gotofail:RPKX6AZBeUvMjVQPEdoCn1Vq
    email: false
cache:
    directories:
        - node_modules
        - bower_components
